/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.celeoproc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        CeleoprocApp classUnderTest = new CeleoprocApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
